### ISSUE TITLE
`nix flake check` and rebuild fails after update

### ISSUE THREAD

**Issue by maksalees** [SenchoPens/base16.nix#4] opened 2023-06-04 15:33 UTC
```
error:
       … while checking flake output 'nixosConfigurations'

         at /nix/store/z7bz1jaafr7mxi9swrk684cgn25zbava-source/flake.nix:39:5:

           38|   outputs = { self, nixpkgs, ... } @ inputs: {
           39|     nixosConfigurations = import ./hosts inputs;
             |     ^
           40|   };

       … while checking the NixOS configuration 'nixosConfigurations.noelle'

         at /nix/store/z7bz1jaafr7mxi9swrk684cgn25zbava-source/hosts/default.nix:19:5:

           18|   in {
           19|     noelle = nixpkgs.lib.nixosSystem {
             |     ^
           20|       inherit system;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute '"\""' missing

       at /nix/store/4wg7s6z4hmv6x7a8nzr6nznd1mz0x5cw-source/default.nix:23:12:

           22|     in
           23|       16 * hex2decDigits."${builtins.substring 0 1 hex}"
             |            ^
           24|       + hex2decDigits."${builtins.substring 1 2 hex}";
       Did you mean one of 0, 1, 2, 3 or 4?
```

**Comment by SenchoPens** [comment] 2023-06-04 18:56
Hi @maksalees, thank you for reporting this. I was expecting this sort of issues to happen :(

It seems that's the problem is in your scheme file, can you please share it?

Meanwhile doing something like this might fix it:
```nix
config.scheme = config.lib.base16.yaml2attrs-ifd "${inputs.base16-schemes}/nord.yaml";
```
(see https://github.com/SenchoPens/base16.nix#%EF%B8%8F-troubleshooting for more info).

**Comment by maksalees** [comment] 2023-06-04 20:06
It worked, thanks. I use https://github.com/dracula/base16-dracula-scheme

**Comment by SenchoPens** [comment] 2023-06-04 20:59
Nice, I'll fix the YAML parser that causes the error when I have time and then I'll close this issue.

**Comment by SenchoPens** [comment] 2023-07-16 23:39
Hi @maksalees, I believe I fixed it. Can you try the latest release?

**Comment by maksalees** [comment] 2023-07-17 12:53
> Hi @maksalees, I believe I fixed it. Can you try the latest release?

Yes, this fixed it. Thank you

**Closed as completed** 2023-07-17 13:11 UTC
